version: "3.9"

services:
  relay:
    container_name: smtp-relay
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    environment:
      - SSL_CERT_PATH=/certs/cert.pem
      - SSL_KEY_PATH=/certs/key.pem
    volumes:
      - ./certs:/certs
    ports:
      - "1025:1025"
    restart: unless-stopped
